require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle}'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 100
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 10