require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - "vendor/**/*"
    - "bin/{rails,rake,bundle,brakeman,bundle-audit,bundler-audit,rubocop}"

Style/Documentation:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Max: 100
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 10

# TODO: Enable after tests are fixed
RSpec/EmptyExampleGroup:
  Enabled: false
