# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/heartbeat_destinations', type: :request do
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      HeartbeatDestination.create! valid_attributes
      get heartbeat_destinations_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      heartbeat_destination = HeartbeatDestination.create! valid_attributes
      get heartbeat_destination_url(heartbeat_destination)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_heartbeat_destination_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      heartbeat_destination = HeartbeatDestination.create! valid_attributes
      get edit_heartbeat_destination_url(heartbeat_destination)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new heartbeat_destination' do
        expect do
          post heartbeat_destinations_url, params: { heartbeat_destination: valid_attributes }
        end.to change(HeartbeatDestination, :count).by(1)
      end

      it 'redirects to the created heartbeat_destination' do
        post heartbeat_destinations_url, params: { heartbeat_destination: valid_attributes }
        expect(response).to redirect_to(heartbeat_destination_url(HeartbeatDestination.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new heartbeat_destination' do
        expect do
          post heartbeat_destinations_url, params: { heartbeat_destination: invalid_attributes }
        end.to change(HeartbeatDestination, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post heartbeat_destinations_url, params: { heartbeat_destination: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested heartbeat_destination' do
        heartbeat_destination = HeartbeatDestination.create! valid_attributes
        patch heartbeat_destination_url(heartbeat_destination), params: { heartbeat_destination: new_attributes }
        heartbeat_destination.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the heartbeat_destination' do
        heartbeat_destination = HeartbeatDestination.create! valid_attributes
        patch heartbeat_destination_url(heartbeat_destination), params: { heartbeat_destination: new_attributes }
        heartbeat_destination.reload
        expect(response).to redirect_to(heartbeat_destination_url(heartbeat_destination))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        heartbeat_destination = HeartbeatDestination.create! valid_attributes
        patch heartbeat_destination_url(heartbeat_destination), params: { heartbeat_destination: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested heartbeat_destination' do
      heartbeat_destination = HeartbeatDestination.create! valid_attributes
      expect do
        delete heartbeat_destination_url(heartbeat_destination)
      end.to change(HeartbeatDestination, :count).by(-1)
    end

    it 'redirects to the heartbeat_destination list' do
      heartbeat_destination = HeartbeatDestination.create! valid_attributes
      delete heartbeat_destination_url(heartbeat_destination)
      expect(response).to redirect_to(heartbeat_destinations_url)
    end
  end
end
