name: CI
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          rubygems: latest
          bundler: latest
          bundler-cache: true
          cache-version: 3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: yarn

      - name: Install yarn packages
        run: |
          yarn install --frozen-lockfile

      - name: Run linters
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          LOCKBOX_MASTER_KEY: ${{ secrets.LOCKBOX_MASTER_KEY }}
        run: |
          bin/rubocop --config .rubocop.yml -P -f github
          yarn prettier --check .
          yarn run eslint

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          rubygems: latest
          bundler: latest
          bundler-cache: true
          cache-version: 3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: yarn

      - name: Install yarn packages
        run: |
          yarn install --frozen-lockfile

      - name: Run security checks
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          LOCKBOX_MASTER_KEY: ${{ secrets.LOCKBOX_MASTER_KEY }}
        run: |
          bin/bundler-audit --update
          bin/brakeman -q --no-pager

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: detonate
          POSTGRES_DB: detonate_test
          POSTGRES_PASSWORD: detonate
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          rubygems: latest
          bundler: latest
          bundler-cache: true
          cache-version: 3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: yarn

      - name: Install yarn packages
        run: |
          yarn install --frozen-lockfile

      - name: Run tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          LOCKBOX_MASTER_KEY: ${{ secrets.LOCKBOX_MASTER_KEY }}
          POSTGRES_PASSWORD: detonate
          DATABASE_URL: postgres://detonate:detonate@127.0.0.1:5432/detonate_test
        run: |
          bundle exec rails db:setup
          bundle exec rails assets:precompile
          bundle exec rspec
